# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-10 21:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_emision', models.DateField()),
                ('fecha_expiracion', models.DateField()),
                ('valido', models.BooleanField()),
                ('id_ticket', models.PositiveIntegerField()),
            ],
        ),
    ]
