# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-18 02:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('casino', '0003_auto_20171011_1946'),
    ]

    operations = [
        migrations.CreateModel(
            name='Codigo_Promocion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Promocion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_expiracion', models.DateField()),
                ('fecha_emision', models.DateField()),
                ('meta', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=500)),
                ('image', models.BinaryField(blank=True, default=None)),
            ],
        ),
        migrations.AddField(
            model_name='codigo_promocion',
            name='promocion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='casino.Promocion'),
        ),
    ]
