# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-18 03:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casino', '0004_auto_20171018_0258'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promocion',
            name='image',
        ),
        migrations.AddField(
            model_name='promocion',
            name='imagen',
            field=models.BinaryField(blank=True, default=None, null=True),
        ),
    ]
